### ISSUE TITLE
Unused variable in shop.js .. potentially a bug

### ISSUE THREAD

**Issue by nahilep** [RanvierMUD/bundle-example-vendors#1]
https://github.com/RanvierMUD/bundle-example-vendors/blob/master/commands/shop.js#L169

This line assumes that only the first word of the args is the item to be appraised. What about the `copper sword`? I think it would only search for `copper` in a players inventory.

I think this line can be deleted and in the next line change `itemArg` to `args`

**Comment by shawncplus** [comment]
Most commands that take a target argument only take the first word. I can't think of any command in the example bundles that actually expects `<command> copper sword`. They look for `<command> copper` and `sword` is thrown away. Once I move the command parser out of core this will be up to the bundles anyway.

With that said the `confirm` variable in that particular code is, as you said, unused.
